[[colony]]
copies = 30
initial_size = 1
[[colony.treatment]]
name = "Control"
added_on_frame = 0

[colony.treatment.division_curve]
name = "Gamma"
mean = 16.23
std = 2.84
a = 3.32
[colony.treatment.death_curve]
name = "Gaussian"
mean = 100.0
std = 1.0
[[colony.treatment]]
name = "Temozolomide"
added_on_frame = 72

[colony.treatment.division_curve]
name = "EMGaussian"
mean = 12.72
std = 8.5
k = 2.87
[colony.treatment.death_curve]
name = "EMGaussian"
mean = 55.09
std = 23.75
k = 2.93

[colony.cells]
radius = 20.0
max_speed = 0.020351
linked_sister_inheritance = true
mother_fitness_memory = 0.0
sister_fitness_memory = 0.0
[colony.cells.signal]
name = "Gaussian"
initial_value = 0.0
std = 0.05
