verbose = true
delta = 3600

[well]
well_radius = 13351.624

[output]
output_folder = 'output'
parameters_file_name = 'params.json'
cell_csv_file_name = 'cell_output.csv'
colony_csv_file_name = 'colony_output.csv'
confirm_overwrite = false

[stop_conditions]
stop_at_frame = 144
#stop_at_single_colony_size = 50
#stop_at_all_colonies_size = 8
