[[colony]]
copies = 1
initial_size = 8

  [colony.cells]
  radius = 20
  max_speed = 0.020351
  linked_sister_inheritance = false  # if true, the second child cell inherits from the first upon division
  mother_fitness_memory = 0.0  # between 0 and 1
  sister_fitness_memory = 0.0  # between 0 and 1

  [[colony.treatment]]
  name = 'treat'
  added_on_frame = 0
    [colony.treatment.division_curve]
    name = 'Gaussian'
    mean = 24.0
    std = 3.0
    [colony.treatment.death_curve]
    name = 'Gaussian'
    mean = 28.0
    std = 3.0

#  [[colony.treatment]]
#  name = 'Temozolomide'
#  added_on_frame = 72
#    [colony.treatment.division_curve]
#    name = 'EMGaussian'
#    mean = 12.72
#    std = 8.50
#    k = 2.87
#    [colony.treatment.death_curve]
#    name = 'EMGaussian'
#    mean = 55.09
#    std = 23.75
#    k = 2.93
