[[colony]]
copies = 106
initial_size = 1

  [colony.cells]
  radius = 20  # im µm
  max_speed = 0.0  # in µm/s
  linked_sister_inheritance = true  # if true, the second child cell inherits from the first upon division
  mother_fitness_memory = 0  # between 0 and 1
  sister_fitness_memory = 0  # between 0 and 1
    [colony.cells.signal]
    name = 'Gaussian'
    initial_value = 0.0  # between -1 and 1
    std = 0.05

  [[colony.treatment]]
  name = 'Control'
  added_on_frame = 0
  # fitness_memory_disturbance = 0.5  # new fitness memory after applying treatment
    # [colony.treatment.signal_disturbance]  # new signal after applying treatment
    # name = 'Gaussian'
    # initial_value = 0.0
    # std = 0.15
    [colony.treatment.division_curve]
    name = 'Gamma'
    mean = 13.2
    std = 1.1
    # k = 1.0  # for EMGaussian only
    a = 3.32  # for Gamma only
    # s = 1.0  # for Lognormal only
    [colony.treatment.death_curve]
    name = 'Gaussian'
    mean = 26.1
    std = 6.4
    k = 1.0  # for EMGaussian only
    # a = 1.0  # for Gamma only
    # s = 1.0  # for Lognormal only

  [[colony.treatment]]
  name = 'Temozolomide'
  added_on_frame = 144
  # fitness_memory_disturbance = 0.5  # new fitness memory after applying treatment
    # [colony.treatment.signal_disturbance]  # new signal after applying treatment
    # name = 'Gaussian'
    # initial_value = 0.0
    # std = 0.15
    [colony.treatment.division_curve]
    name = 'EMGaussian'
    mean = 13.2
    std = 1.1
    # k = 2.87  # for EMGaussian only
    # a = 1.0  # for Gamma only
    # s = 1.0  # for Lognormal only
    [colony.treatment.death_curve]
    name = 'EMGaussian'
    mean = 26.091
    std = 6.4
    # k = 2.93  # for EMGaussian only
    # a = 1.0  # for Gamma only
    # s = 1.0  # for Lognormal only

# [[colony]]  # define additional colonies here
